import matplotlib.pyplot as plt
import numpy as np
import matplotlib.gridspec as gridspec

x = np.linspace(-5,5,500)

fig = plt.figure(tight_layout=True)
gs = gridspec.GridSpec(3, 4)

ax = fig.add_subplot(gs[0, 0])
ax.set_title("Cuadratica")
ax.plot(x, x**2, color='red')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[0, 1])
ax.set_title("Cubica")
ax.plot(x, x**3, color='coral')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[0, 2])
ax.set_title("Polinomial")
ax.plot(x, (x**4 + x**3 - 6*x**2 - 27*x + 3), color='orange')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[0, 3])
ax.set_title("Racional")
ax.plot(x, (x/(x**2 + 1)), color='gold')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[1, 0])
ax.set_title("Exponencial")
ax.plot(x, (1.5**x), color='lawngreen')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[1, 1])
ax.set_title("Logaritmica")
plt.ylim(-5, np.e)
plt.xlim(np.e**(-7), 5)
ax.plot(x, (np.log(x)), color='springgreen')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[1, 2])
ax.set_title("Seno")
ax.plot(x, (np.sin(x)), color='turquoise')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[1, 3])
ax.set_title("Coseno")
ax.plot(x, (np.cos(x)), color='cyan')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[2, 0])
ax.set_title("Tangente")
plt.ylim(-10, 10)
plt.xlim(-1.5, 1.5)
ax.plot(x, (np.tan(x)), color='blue')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[2, 1])
ax.set_title("Cotengente")
plt.ylim(-10, 10)
plt.xlim(-3.14, -0.05)
ax.plot(x, (1/(np.tan(x))), color='blueviolet')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[2, 2])
ax.set_title("Secante")
plt.ylim(0, 3)
plt.xlim(-1.5, 1.5)
ax.plot(x, (1/(np.cos(x))), color='magenta')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()

ax = fig.add_subplot(gs[2, 3])
ax.set_title("Cosecante")
plt.ylim(-3, 0)
plt.xlim(-3.14, -0.05)
ax.plot(x, (1/(np.sin(x))), color='crimson')
ax.set_ylabel('$f(x)$')
ax.set_xlabel('$x$')
ax.grid()


fig.align_labels()
plt.show()
